[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = ""
  exclude = [
    # By file Path
    './athletics.html',
    './cricket.html',
    './football.html',
    './rugby.html',
    './hockey-wales.html',
    './terv.html',
    './release-notes.html',
    './404.html',
    './401.html',
    './plugins/**'
    ]

[[plugins]]
package = "/plugins/image-to-webp"
  [plugins.inputs]
  fileLevel = "/opt/build/repo"
  imagePath = "/opt/build/repo/images/webp"
