[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    './public/athletics.html',
    './public/cricket.html',
    './public/football.html',
    './public/rugby.html',
    './public/hockey-wales.html',
    './public/pricing.html'
    ]
