[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = ""
  exclude = [
    # By file Path
    './athletics.html',
    './cricket.html',
    './football.html',
    './rugby.html',
    './hockey-wales.html',
    './terv.html',
    './release-notes.html',
    './404.html',
    './401.html',
    './plugins/image-to-webp/node_modules/has-symbol-support-x/badges$',
    './plugins/image-to-webp/node_modules/has-to-string-tag-x/badges$',
    './plugins/image-to-webp/node_modules/has-symbol-support-x/tests$',
    './plugins/image-to-webp/node_modules/console-stream/test/static$'
    ]

[[plugins]]
package = "/plugins/image-to-webp"
  [plugins.inputs]
  fileLevel = "/opt/build/repo"
  imagePath = "/opt/build/repo/images/webp"
